enum CloudFramerIntAttr
{
	GridWidth			,
	GridHeight			,
	Use3DNoise			,
	Wrap				,
	NoiseResolution		,
	OverrideWind		,
	EdgeNoiseOctaves	,
	EdgeNoiseFrequency	,
	EdgeNoiseTextureSize,
	ExplicitOffsets		,
	ShadowTextureSize	,
	GodraysSteps		,
	DefaultNumSlices	,
	Visible				,
	MeetHorizon			,
	cloudIntAttrSize		
};

enum CloudFrameFloatAttr
{
	cloudiness				,
	distributionBaseLayer	,
	distributionTransition	,
	upperDensity			,
	localDensity			,
	windSpeed				,
	windDirection			,
	persistence				,
	cloudBase				,
	cloudHeight				,
	directLight				,
	indirectLight			,
	ambientLight			,
	lightAsymmetry			,
	precipitation			,
	fractalWavelength		,
	fractalAmplitude		,
	edgeSharpness			,
	churn					,
	extinction				,
	rainToSnow				,
	precipitationWindEffect	,
	precipitationWaver		,
	diffusivity				,
	cache_built				,
	lightning				,
	godrayStrength			,
	baseNoiseFactor			,
	offsetx					,
	offsety					,
	rainCentreXKm			,
	rainCentreYKm			,
	rainRadiusKm			,
	rainEffectStrength		,
	simulation				,
	worleyNoise				,
	worleyScale				,
	cloudFloatAttrSize		
};